/**
 * gtwo-kml.js — NHC's Graphical Tropical Weather Outlook, read from the KML
 * inside the KMZ. SPEC-DATA §45.2.
 *
 * ==> THIS IS THE SAME PRODUCT AS GIS LAYER 3, PUBLISHED BETTER. <== Not a
 * second opinion, not a fallback — the same forecaster run, from the same
 * minute, put on a different path. Measured across all 72 hours in the archive
 * window on 2026-08-19: identical vertex counts, agreeing to roughly nine
 * decimal places, and the issue stamp matching layer 3's `idp_source` to the
 * minute every single hour. Layer 3's `gtwo_areas_202608190525` is this file's
 * `Wed Aug 19 05:25:08 2026`.
 *
 * ==> IT CARRIES FOUR THINGS LAYER 3 DOES NOT, AND TWO OF THEM UNDO DECISIONS
 *     THIS PROJECT MADE ONLY BECAUSE THEY WERE MISSING. <==
 *
 * 1. NHC'S OWN NAME FOR THE AREA. `South-Southwest of Mexico`. Layer 3
 *    publishes no name, which is the entire reason `lib/genesis.js` computes a
 *    description from the centroid and says so in capitals.
 *
 * 2. A DISTURBANCE NUMBER ON EVERY PLACEMARK, which joins an area to its
 *    current-position point. The `GENESIS` block in config/constants.js records
 *    layer 2 as never fetched precisely because the two GIS layers cannot be
 *    matched — anchor 1 carrying polygon 2's attributes while sitting inside
 *    polygon 1. Here the join is published rather than inferred, so the
 *    failure that measurement describes cannot happen.
 *
 * 3. THE FORECASTER'S PARAGRAPH, attached to the polygon it describes.
 *    `lib/outlook.js` explains at length why the text bulletin's areas can
 *    never be matched to polygons — titles genuinely collide. Here no matching
 *    is required, because the prose is inside the shape.
 *
 * 4. AN UNLABELLED `LineString`. See `tracks` below, and read the caveat.
 *
 * ==> AND IT SAYS THE ALL-CLEAR IN WORDS. <== An empty FeatureCollection is
 * unstamped: "NHC is watching nothing" and "NHC's layer is broken" are the
 * same bytes, which is the 2026-08-11 incident in one sentence. This document
 * carries `Tropical cyclone formation is not expected` as a sentence in a
 * basin that has nothing. That is a fact, not an absence, and §45.5's held
 * branch exists only because layer 3 could not produce one.
 *
 * ==> WHY THERE IS NO XML PARSER HERE. <== `DOMParser` does not exist in
 * workerd, and this has to run in the relay as well as in a test. The document
 * is machine-generated by NHC on a fixed template — no namespaces on the
 * elements that matter, no CDATA, no attributes carrying values, four element
 * shapes total. A scan is honest about that; a hand-rolled general XML parser
 * would be pretending to more than it does.
 *
 * Pure and synchronous, like `lib/outlook.js` and `lib/abpw.js`: text in,
 * state out, never throws, no fetching. `_kmz.js` unwraps the container (§4 —
 * that is transport); this interprets.
 *
 * ==> WHY IT IS UNDER functions/ RATHER THAN lib/, which is where README puts
 * parsers. <== The same reason `_ships-parse.js` next door is: a KMZ is a zip
 * of five entries and 45% of its bytes are icons nobody will ever draw, so the
 * unwrapping belongs on the far side of the relay and the browser should
 * receive the small GeoJSON. Leaving a working client-side copy in `lib/`
 * would put a second implementation of this judgement on the other side of a
 * deploy boundary — the exact drift §4.3 and `worker/src/sources.js` refuse to
 * commit — and would invite somebody to fetch the KMZ from a phone. There is
 * ONE of these and the browser cannot reach it. `_` is Cloudflare's
 * not-a-route marker; `tools/check-syntax.mjs` covers these files anyway.
 *
 * ==> AND THE PARSE STILL DECIDES NOTHING, which is what keeps §4.3's rule
 * intact. <== It converts a container and a fixed template into the same
 * FeatureCollection the GIS layer published. Every judgement about basin,
 * colour, ordering, staleness and wording still runs in `lib/genesis.js` and
 * `lib/outlook.js` in the browser, exactly as before.
 *
 * Imports nothing. Never DOM, never data/, never map/, never ui/.
 */

/* --- the little bit of XML we actually need -------------------------------- */

/** The five entities NHC's generator emits, and no others. Ampersand is
 *  replaced LAST or `&amp;lt;` decodes twice into a tag. */
function decodeEntities(text) {
  return String(text)
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&amp;/g, '&');
}

/** The text of the first `<tag>` in a chunk, decoded, or null. */
function tagText(chunk, tag) {
  const m = chunk.match(new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)</${tag}>`));
  return m ? decodeEntities(m[1]).trim() : null;
}

/** One `<Data name="...">`'s value, decoded, or null. Whitespace inside the
 *  value is left exactly as NHC wrote it — the discussion's line breaks are
 *  the forecaster's and squashing them here would make them unrecoverable. */
function dataValue(chunk, name) {
  const m = chunk.match(
    new RegExp(`<Data\\s+name="${name}"\\s*>[\\s\\S]*?<value>([\\s\\S]*?)</value>`)
  );
  return m ? decodeEntities(m[1]) : null;
}

/**
 * A `<coordinates>` block → `[[lon, lat], ...]`.
 *
 * KML writes `lon,lat,altitude` and altitude is always zero here. Anything
 * that is not two finite numbers is dropped rather than passed on as NaN,
 * which would put a vertex at the centre of the earth and take the whole
 * polygon with it.
 */
function coordinates(chunk) {
  const raw = chunk.match(/<coordinates>([\s\S]*?)<\/coordinates>/);
  if (!raw) return [];
  const out = [];
  for (const triple of raw[1].trim().split(/\s+/)) {
    const [lon, lat] = triple.split(',');
    const x = Number(lon);
    const y = Number(lat);
    if (Number.isFinite(x) && Number.isFinite(y)) out.push([x, y]);
  }
  return out;
}

/* --- the document header --------------------------------------------------- */

const MONTHS = Object.freeze({
  Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5,
  Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11,
});

/**
 * `Wed Aug 19 05:25:08 2026` → epoch milliseconds, or null.
 *
 * ==> IT IS PARSED BY HAND BECAUSE `Date.parse` WOULD READ IT AS LOCAL TIME.
 * <== The string carries no zone. It is UTC — layer 3 stamped the same run
 * `gtwo_areas_202608190525` and NHC's text bulletin headed it `190523`, both
 * UTC, checked on four separate advisories. Handing it to `Date.parse` on a
 * phone in Honolulu would date the outlook ten hours late and make every fresh
 * one look stale.
 */
export function parseIssuedAt(name) {
  const m = String(name ?? '').match(
    /\b[A-Z][a-z]{2}\s+([A-Z][a-z]{2})\s+(\d{1,2})\s+(\d{2}):(\d{2}):(\d{2})\s+(\d{4})\b/
  );
  if (!m) return null;
  const month = MONTHS[m[1]];
  if (month == null) return null;
  return Date.UTC(Number(m[6]), month, Number(m[2]), Number(m[3]), Number(m[4]), Number(m[5]));
}

/**
 * Which basin this document is for.
 *
 * NHC spells it in the document title — `North Atlantic basin`, `eastern North
 * Pacific basin`. Matched loosely on the ocean word, because the qualifiers in
 * front of it have changed before and the ocean has not. Unrecognised is
 * reported as `null` and never guessed: filing Pacific areas against an
 * Atlantic bulletin is worse than filing them nowhere.
 *
 * The keys match `lib/outlook.js`'s basins so the two products can be compared
 * without a translation table between them.
 */
export function parseBasin(name) {
  const t = String(name ?? '');
  if (/\bAtlantic\b/i.test(t)) return 'atlantic';
  if (/\bPacific\b/i.test(t)) return 'epacific';
  return null;
}

/**
 * The all-clear sentence, matched the same loose way `lib/outlook.js` matches
 * it in the text product — and for the same reason. NHC has spelled the
 * horizon `5 days` and `7 days` in different eras, so the number is not
 * pinned; the sentence is about formation not being expected, and that clause
 * is what is looked for.
 */
const NOT_EXPECTED_RE = /formation\s+is\s+not\s+expected/i;

/* --- one placemark --------------------------------------------------------- */

/**
 * `1. South-Southwest of Mexico: An area of low pressure...` → the title.
 *
 * ==> THIS IS NHC'S NAME AND NOT OURS, WHICH IS THE WHOLE POINT. <== The
 * leading number is the disturbance number repeated, and it is stripped
 * because it is already carried as a field; printing "1." in front of a name
 * would look like a rank. The split is on the FIRST colon, which is where the
 * template puts it — measured on every area in the archive window.
 *
 * A discussion that does not match the template returns null rather than a
 * best guess. A wrong name on an area is the §5 failure that looks perfect on
 * screen, and `lib/genesis.js` already has a description to fall back to.
 */
export function titleFromDiscussion(discussion) {
  const first = String(discussion ?? '').trim().split('\n')[0] || '';
  const m = first.match(/^\s*\d+\.\s*([^:]{2,80}):/);
  return m ? m[1].trim() : null;
}

/**
 * `1. South of Mexico: An area of low pressure...` -> `An area of low
 * pressure...`, and only when the prefix is exactly the title already read off
 * it. Anything else is returned untouched.
 */
export function stripTitlePrefix(discussion, title) {
  const text = discussion == null ? null : String(discussion).trim();
  if (!text || !title) return text || null;
  const cut = text.replace(
    new RegExp(`^\\s*\\d+\\.\\s*${title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*:\\s*`),
    ''
  );
  return cut.trim() || null;
}

/** Everything a placemark says about itself, geometry aside. */
function attributes(chunk) {
  const discussion = dataValue(chunk, 'Discussion');
  const title = titleFromDiscussion(discussion);
  return {
    disturbance: (() => {
      const n = Number(dataValue(chunk, 'Disturbance'));
      return Number.isInteger(n) && n > 0 ? n : null;
    })(),
    prob2day: dataValue(chunk, '2day_percentage'),
    risk2day: dataValue(chunk, '2day_category'),
    prob7day: dataValue(chunk, '7day_percentage'),
    risk7day: dataValue(chunk, '7day_category'),
    /* ==> THE `2. South-Southwest of Mexico:` PREFIX IS STRIPPED HERE. <== It
     * is packaging, not content: NHC's plain-text bulletin publishes these
     * paragraphs with no number at all — `samples/outlook-text/` has the bytes
     * — and the numbering is something the KMZ generator adds. Left on, the
     * paragraph opens by restating the heading directly above it with a rank
     * in front, which reads as a ranking NHC never published.
     *
     * REMOVED ONLY WHEN IT IS EXACTLY THE TITLE WE ALREADY EXTRACTED. If the
     * template ever changes and `titleFromDiscussion` returns null, nothing is
     * cut — the whole paragraph survives with its prefix rather than having
     * its first sentence guessed at and deleted. */
    discussion: stripTitlePrefix(discussion, title),
    title,
  };
}

/* --- the document ---------------------------------------------------------- */

/**
 * A GTWO KML → what it says.
 *
 * NEVER THROWS. Unreadable input comes back as `state: 'unreadable'` with a
 * reason, because the caller's choice between "NHC is watching nothing" and
 * "we could not read NHC" is the single decision this whole feature turns on,
 * and an exception makes those two look alike in a catch block.
 *
 * Returns:
 *   state                'ok' | 'unreadable'
 *   reason               a sentence, when unreadable
 *   basin                'atlantic' | 'epacific' | null
 *   issuedAt             epoch ms, or null
 *   formationNotExpected true when the document states the all-clear
 *   areas                the watched polygons, in document order
 *   anchors              current-position points, each with its disturbance
 *   tracks               see the caveat below
 */
export function parseGtwoKml(text) {
  const raw = String(text ?? '');
  if (!raw.trim()) return { state: 'unreadable', reason: 'The outlook document was empty.' };
  if (!/<kml\b/i.test(raw) || !/<Document\b/i.test(raw)) {
    return { state: 'unreadable', reason: 'That is not a KML document.' };
  }

  /* The Document's own name, not a Placemark's — the first `<name>` in the
   * file, which the template puts above every placemark. */
  const name = tagText(raw, 'name');
  const description = raw.match(/<description>([\s\S]*?)<\/description>/);

  const areas = [];
  const anchors = [];
  const tracks = [];

  for (const m of raw.matchAll(/<Placemark>([\s\S]*?)<\/Placemark>/g)) {
    const chunk = m[1];
    const points = coordinates(chunk);
    if (!points.length) continue;

    if (/<Polygon>/.test(chunk)) {
      /* Outer boundary only. NHC has never published an inner ring on one of
       * these — a development region with a hole in it would be a strange
       * thing to forecast — and reading one that does not exist is how a
       * parser invents geometry. If one ever appears it is dropped, visibly,
       * rather than silently merged into the outer ring. */
      areas.push({ ...attributes(chunk), ring: points });
    } else if (/<LineString>/.test(chunk)) {
      /* ==> UNLABELLED, AND CARRIED WITHOUT A NAME ON PURPOSE. <== It has no
       * `<name>`, no `ExtendedData` and no disturbance number. Measured on
       * 2026-08-19 across the archive window: present in 23 of 72 hours, and
       * in the four hours examined closely it was there exactly when a
       * disturbance's current position sat OUTSIDE its own watched area and
       * absent when the position was inside — starting about half a degree
       * ahead of that position and running roughly six degrees
       * west-northwest. That reads like a short motion path. FOUR SAMPLES,
       * ONE DISTURBANCE, ONE BASIN. Nothing may call it a track on screen
       * until it has been seen on another storm in another basin. */
      tracks.push({ line: points });
    } else if (/<Point>/.test(chunk)) {
      const attrs = attributes(chunk);
      /* The all-clear is drawn as two label placemarks holding a sentence and
       * no data. They are not positions and must not become dots. */
      if (attrs.disturbance == null) continue;
      anchors.push({ ...attrs, lon: points[0][0], lat: points[0][1] });
    }
  }

  return {
    state: 'ok',
    documentName: name,
    basin: parseBasin(name),
    issuedAt: parseIssuedAt(name),
    formationNotExpected: NOT_EXPECTED_RE.test(`${name ?? ''}\n${description ? description[1] : ''}`),
    areas,
    anchors,
    tracks,
  };
}

/* --- the shape the rest of the app already reads --------------------------- */

/** How a basin is spelled inside an area's id. Short, stable, and ours. */
const BASIN_KEY = Object.freeze({ atlantic: 'atl', epacific: 'epac' });

/**
 * A parsed document → the FeatureCollection `normalizeNhcAreas` already takes.
 *
 * ==> THE ID IS NAMESPACED BY BASIN, AND THAT IS A FIX RATHER THAN A CHORE.
 * <== Layer 3 answered both basins from one query, so its ArcGIS row numbers
 * happened to be unique across them. The KMZ is published per basin and both
 * documents number their disturbances from 1, so passing the bare number
 * through would give an Atlantic area and a Pacific area the same id and let
 * one replace the other in any map keyed on it. `atl-1` and `epac-1` cannot
 * collide. It is also steadier than what it replaces: a disturbance number
 * belongs to the disturbance, where an ArcGIS row number belongs to the row
 * and is free to change when the outlook republishes.
 *
 * `idp_source` is DELIBERATELY NOT SPELLED THE WAY LAYER 3 SPELLS IT. That
 * field is provenance, it is displayed nowhere, and writing `gtwo_areas_...`
 * here would make a value we synthesised indistinguishable from one NHC
 * published. `gtwo_kml_...` is the same information and is honest about where
 * it came from.
 */
export function toAreaCollection(parsed) {
  if (!parsed || parsed.state !== 'ok') return { type: 'FeatureCollection', features: [] };

  const key = BASIN_KEY[parsed.basin] || 'unknown';
  const stamp = parsed.issuedAt == null
    ? null
    : `gtwo_kml_${new Date(parsed.issuedAt).toISOString().slice(0, 16).replace(/[-:T]/g, '')}`;

  const features = parsed.areas.map((area) => ({
    type: 'Feature',
    geometry: { type: 'Polygon', coordinates: [area.ring] },
    properties: {
      objectid: `${key}-${area.disturbance ?? 0}`,
      basin: parsed.basin === 'atlantic' ? 'Atlantic' : 'Pacific',
      prob2day: area.prob2day,
      risk2day: area.risk2day,
      prob7day: area.prob7day,
      risk7day: area.risk7day,
      idp_source: stamp,
      idp_filedate: parsed.issuedAt,

      /* The new facts. Carried through the same shape so nothing downstream
       * needs a second source to consult, and named for what they are. */
      nhcTitle: area.title,
      discussion: area.discussion,
      disturbance: area.disturbance,
    },
  }));

  return { type: 'FeatureCollection', features };
}
