#!/usr/bin/env node
/**
 * spec-index.mjs — build SPEC-INDEX.md, the address book for the spec.
 *
 * WHY THIS EXISTS
 * The spec is ~680 KB across eight files. No session can hold that. But section
 * numbers are permanent addresses — code comments say "SPEC §17.7" and mean it.
 * This turns a section number into a file and a line range, so a session runs
 * `sed -n '442,713p' SPEC-OPS.md` instead of reading 61 KB to find one heading.
 *
 * WHAT IT DOES
 * Scans every spec file for numbered markdown headings (## 17. Foo, ### 17.7 Bar)
 * and writes SPEC-INDEX.md: section number -> file, line range, title.
 *
 * IT ALSO POLICES THE ADDRESSES
 * A section number living in two files for real is a bug — the address stops
 * being unique and a §-reference in code becomes ambiguous. That exits non-zero
 * so CI catches it. SPEC.md's deliberate "**Moved to SPEC-DATA.md**" stubs and
 * "*retired*" markers are recognised as signposts, not second homes, and are
 * listed with an arrow instead.
 *
 * Zero dependencies. Run: node tools/spec-index.mjs [--check]
 *   --check  verify SPEC-INDEX.md is current without rewriting it (for CI)
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(REPO, 'SPEC-INDEX.md');

/* A spec file is any top-level *.md whose name starts with SPEC or spec-,
   plus NOW.md. README.md is orientation, not addressable spec. */
const isSpecFile = (name) =>
  name.endsWith('.md') &&
  name !== 'SPEC-INDEX.md' &&
  (/^SPEC/.test(name) || /^spec-/.test(name) || name === 'NOW.md');

/* ## 17. Public operation      -> 17
   ### 17.7 The origin collapse -> 17.7
   #### 6.1.2 Whatever          -> 6.1.2
   The trailing period after a top-level number is inconsistent in the wild,
   so it is tolerated either way. */
const HEADING = /^(#{1,6})\s+(\d+(?:\.\d+)*)\.?\s+(\S.*?)\s*$/;

/* A signpost is a heading whose whole body says "this moved" or "this is
   retired". It holds the address open but is not where the content lives.
   Deliberate, and all over SPEC.md. */
const POINTER = /\*\*Moved to\s+`?([A-Za-z0-9.\-]+\.md)`?/i;
const RETIRED = /\*retired\*/i;

function classify(bodyLines) {
  const body = bodyLines.join('\n').trim();
  const m = POINTER.exec(body);
  if (m) return { kind: 'pointer', target: m[1] };
  if (body.length < 600 && RETIRED.test(body)) return { kind: 'retired' };
  return { kind: 'canonical' };
}

function collect() {
  const files = readdirSync(REPO)
    .filter((n) => statSync(join(REPO, n)).isFile() && isSpecFile(n))
    .sort();

  const entries = [];
  for (const file of files) {
    const lines = readFileSync(join(REPO, file), 'utf8').split('\n');
    /* Every heading, numbered or not — an unnumbered one still ends the
       section above it, so the line range stays honest. */
    const hits = [];
    lines.forEach((line, i) => {
      if (!/^#{1,6}\s/.test(line)) return;
      hits.push({ i, m: HEADING.exec(line) });
    });
    hits.forEach((h, idx) => {
      if (!h.m) return;
      const end = idx + 1 < hits.length ? hits[idx + 1].i : lines.length;
      entries.push({
        section: h.m[2],
        depth: h.m[1].length,
        title: h.m[3].replace(/\s*[—–-]\s*$/, ''),
        file,
        line: h.i + 1,
        endLine: end,
        ...classify(lines.slice(h.i + 1, end)),
      });
    });
  }
  return { files, entries };
}

/* Sort 17.10 after 17.9, not after 17.1 — numeric segment compare. */
function bySection(a, b) {
  const A = a.section.split('.').map(Number);
  const B = b.section.split('.').map(Number);
  for (let i = 0; i < Math.max(A.length, B.length); i++) {
    const d = (A[i] ?? -1) - (B[i] ?? -1);
    if (d) return d;
  }
  return a.file.localeCompare(b.file);
}

/* Only real content colliding is a bug. Signposts are fine. */
function findCollisions(entries) {
  const seen = new Map();
  const bad = [];
  for (const e of entries) {
    if (e.kind !== 'canonical') continue;
    const prev = seen.get(e.section);
    if (prev && prev.file !== e.file) bad.push([prev, e]);
    else if (!prev) seen.set(e.section, e);
  }
  return bad;
}

function render({ files, entries }) {
  /* Canonical home first when a number also has a signpost. */
  const rank = (e) => (e.kind === 'canonical' ? 0 : 1);
  const sorted = [...entries].sort((a, b) => bySection(a, b) || rank(a) - rank(b));

  const out = [];
  out.push('# SPEC-INDEX.md — where every section lives');
  out.push('');
  out.push('**Generated by `tools/spec-index.mjs`. Do not hand-edit — your edit will be');
  out.push('overwritten. Change a heading in the spec and regenerate.**');
  out.push('');
  out.push('Section numbers are permanent addresses. A section can move between files;');
  out.push('it is never renumbered, because code comments reference it. This table turns');
  out.push('`SPEC §17.7` into a file and a line range without reading 61 KB to find it.');
  out.push('');
  out.push('To read one section, the Lines column is ready to paste:');
  out.push('');
  out.push('```');
  out.push('sed -n "442,713p" SPEC-OPS.md');
  out.push('```');
  out.push('');
  out.push(`Covering ${files.length} files, ${sorted.length} numbered headings.`);
  out.push('');
  out.push('An arrow marks a signpost in `SPEC.md` rather than the content itself. The');
  out.push('real home is the other row carrying the same section number.');
  out.push('');
  out.push('## Sections');
  out.push('');
  out.push('| § | Title | File | Lines |');
  out.push('|---|---|---|---|');
  for (const e of sorted) {
    const indent = e.depth > 2 ? '&nbsp;'.repeat((e.depth - 2) * 2) : '';
    const title = e.title.replace(/\|/g, '\\|');
    let where = '`' + e.file + '`';
    let span = `${e.line}-${e.endLine}`;
    if (e.kind === 'pointer') {
      where = '-> `' + e.target + '`';
      span = `${e.file}:${e.line}`;
    } else if (e.kind === 'retired') {
      where = '-> *retired*';
      span = `${e.file}:${e.line}`;
    }
    out.push(`| \`${e.section}\` | ${indent}${title} | ${where} | ${span} |`);
  }
  out.push('');
  out.push('## Files');
  out.push('');
  /* ==> ONLY FILES THAT ACTUALLY CARRY SECTION ADDRESSES ARE LISTED. <==
   *
   * The byte count is regenerated from disk, and `--check` compares the whole
   * rendered file, so ANY listed file changing size makes CI red. That is
   * correct for a spec file — a heading may have moved and the line ranges
   * below would be lying. It is nonsense for a file with zero numbered
   * sections: `NOW.md` is rewritten every session BY DESIGN, and it was
   * turning a routine session note into a failed build with a message about
   * stale section addresses that had not changed. MEASURED 2026-08-11: two
   * pushes in a row went red for exactly this, and the second one was a
   * one-line edit to a file this index does not address into.
   *
   * A check that fails for a reason unrelated to the thing it protects is how
   * a red board stops meaning anything. The size of a file with no sections in
   * it was never the point. */
  const addressed = files.filter(
    (f) => entries.some((e) => e.file === f && e.kind === 'canonical')
  );
  out.push('| File | Bytes | Numbered sections |');
  out.push('|---|---|---|');
  for (const f of addressed) {
    const bytes = statSync(join(REPO, f)).size;
    const n = entries.filter((e) => e.file === f && e.kind === 'canonical').length;
    out.push(`| \`${f}\` | ${bytes.toLocaleString('en-US')} | ${n} |`);
  }
  out.push('');
  return out.join('\n') + '\n';
}

const data = collect();
const collisions = findCollisions(data.entries);
const text = render(data);

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    /* missing counts as stale */
  }
  if (current !== text) {
    console.error('SPEC-INDEX.md is stale. Run: node tools/spec-index.mjs');
    process.exit(1);
  }
  console.log(`SPEC-INDEX.md is current — ${data.entries.length} headings.`);
} else {
  writeFileSync(OUT, text);
  console.log(
    `SPEC-INDEX.md written — ${data.entries.length} headings across ${data.files.length} files.`
  );
}

if (collisions.length) {
  console.error('');
  console.error('SECTION NUMBER COLLISIONS — the same address in two files:');
  for (const [a, b] of collisions) {
    console.error(`  §${a.section}  ${a.file}:${a.line}  AND  ${b.file}:${b.line}`);
  }
  process.exit(1);
}
